=== Canbayraktar/allforone-paypal/target/allforone-paypal/meta-data/schemas/paypallist.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title":"Paypal List",
  "type":"object",
  "properties":
  {
    "clientId":
    {
      "type":"string"
    },
    "clientSecretId":
    {
      "type":"string"
    },
    "createdAt":
    {
      "type":"string",
      "format":"date-time"
    },
    "items":
    {
      "type":"array",
      "items":
      {
        "$ref":"paypalItem"
      }
    }
  },
  "required":["clientId", "clientSecretId"]
}

=== Canbayraktar/allforone-paypal/target/allforone-paypal/meta-data/examples/paypallist-example.json
{
  "clientId":"AeruG19el8CaACWUYEDMyvBXbZlQ07rnPhN8asdR3r43E4ZOKXvFOVZ",
  "clientSecretId":"345MWyh7w4hY98W6",
  "createdAt":"2012-07-12T12:42:23.777Z",
   "items":
    [
      {
        "mode":"sandbox",
        "successUrl":"http://myApi.de/paypalafo/345MWyh7w4hY98W6",
        "cancelUrl":"http://myApi.de/paypalafo/345MWyh7w4hY98W6"
      },
      {
        "mode":"sandbox",
        "successUrl":"http://myApi.de/paypalafo/345MWyh7w4hY98W6",
        "cancelUrl":"http://myApi.de/paypalafo/345MWyh7w4hY98W6"
      }
    ]
}
